version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    working_directory: ~/loner

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "app/Pipfile.lock" }}
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install pipenv
            pipenv install
          environment:
            - PIPENV_PIPFILE: /app/Pipfile
            - PIPENV_VENV_IN_PROJECT: 1

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python manage.py test

      - store_artifacts:
          path: test-reports
          destination: test-reports

      - push_to_registry:
          name: push to docker hub
          command: |
            docker login --username=ceilingcat --password=${DOCKERHUB_CIRCLECI_TOKEN}
            docker push ceilingcat/loner-bot:{{ branch }}